### PR TITLE
Ease use of select2 theme "bootstrap4" (fixes #3)

### LINKED ISSUE #3: Use with bootstrap4 theme?
Hi!

I have been thinking about an easy and maintainable way to use django-simple-select2 with [select2-bootstrap4-theme](https://github.com/ttskch/select2-bootstrap4-theme) to blend into existing projects using Bootstrap 4. It seems to take two things:

1. getting the `.css` file into `.media` of the widget class and
2. passing `theme: "bootstrap4"` to the `.select2(...)` initialization.

For (1) inheriting from `AutocompleteMixin` and overriding `.media` should work. (2) seems more tricky. Replacing `autocomplete.js` altogether would not be too cool but https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/autocomplete.js does not seem to expose options to the outside so I don't see a way around it right now. Any ideas to achieve this in a more simple and more maintainable way?

Are you using Select2 theme `default`? Do you happen to have plans to ship support for bootstrap4 theming out of the box? 

Thanks and best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #3

What do you think?

### CODE REVIEW

**Comment by hartwork** [comment]
Any thoughts?

**Comment by jerinpetergeorge** [comment]
So far so good!! But, It seems the border of the select widget is missing

image

You can reproduce this behaviour by adding the theme arg to the [demo project, here](https://github.com/jerinpetergeorge/simple-select2-demo/blob/9e7820eea01824a67c7867a7dc68d27b92d06024/demo/forms.py#L12)
<pre><code>'reporter': AutoCompleteSelect2(url='select2-reporter-list', <b>theme='bootstrap4'</b>),</code></pre>

**Comment by hartwork** [comment]
You need bootstrap 4 assets as well for it to work. Did you see my pull request https://github.com/jerinpetergeorge/simple-select2-demo/pull/2 over at the demo repo? That's the full picture. My assumption was that someone with a bs4 project has bs4 in their base template somewhere. Does that seem unrealistic to you?

**Comment by jerinpetergeorge** [comment]
wow !!! That amazing.

Would you mind writing a small note/doc regarding this feature in this PR?

**Comment by hartwork** [comment]
> wow !!! That amazing.

Glad that you like it!

Please note that due to https://github.com/jerinpetergeorge/simple-select2-demo/pull/2/files#diff-b4ef698db8ca845e5845c4618278f29aR3 the demo `requirements.txt` with `>0.1.0` only works if there's a new release with bs4 support on PyPI. (I was assuming this PR right here would be the one to merged first.)


> Would you mind writing a small note/doc regarding this feature in this PR?

Let me add a few words on the new settings to the readme as a draft for review.

**Comment by jerinpetergeorge** [comment]
> Please note that due to https://github.com/jerinpetergeorge/simple-select2-demo/pull/2/files#diff-b4ef698db8ca845e5845c4618278f29aR3 the demo `requirements.txt` with `>0.1.0` only works if there's a new release with bs4 support on PyPI. (I was assuming this PR right here would be the one to merged first.)

Yeah... I was aware of that. I am planning to do a release asap with this feature so I hope the version dependency issue won't trigger any headaches for us.

**Comment by hartwork** [comment]
> Let me add a few words on the new settings to the readme as a draft for review.

I have rebased on latest `master` now, pushed one commit preparing the readme for extension and one more with docs on the new settings now. Let me know what you think.

Also, I have added a screenshot to the description of https://github.com/jerinpetergeorge/simple-select2-demo/pull/2 in case you have use for that somewhere later.

**Comment by jerinpetergeorge** [comment]
@hartwork I have release V0.2.0 to PyPI. Thanks for your valuable contribution :+1:

**Comment by hartwork** [comment]
Excellent, thank you!

**Comment by hartwork** [comment]
I noticed that the release notes at https://github.com/jerinpetergeorge/django-simple-select2/releases currently say "bootst[ar]p[-][2]" with three typos in one word. Can you make it `bootstrap4`?

**Comment by jerinpetergeorge** [comment]
Updated. Once again, thanks a lot !!!

**Comment by hartwork** [comment]
Thanks!

**Pull request merged**
